#!/usr/bin/env php
<?php

use Phug\Watcher;

include 'vendor/autoload.php';

$watcher = new Watcher();

$arguments = [];

foreach (array_slice($argv, 1) as $argument) {
    if ($argument === '--exit-on-change') {
        $watcher->setChangeEventCallback(function () {
            exit(0);
        });

        continue;
    }

    $arguments[] = $argument;
}

exit($watcher->watch($arguments) ? 0 : 1);
